version: '3.1'

services:

  web:
    build: ./docker/web
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - ${WEB_ROOT_PATH}:/var/www/html/
    ports:
      - ${WEB_PORT}:80
    working_dir: ${WEB_WORKING_DIR}

  mysql:
    image: mysql:5.7
    restart: ${MYSQL_RESTART}
    volumes:
      - ${MYSQL_PATH}:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: mysql
      PMA_PORT: ${MYSQL_PORT}
    ports:
      - ${PHPMYADMIN_PORT}:80

  mongo:
    image: mongo:4.0-xenial
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ROOT_PASSWORD}
    ports:
      - ${MONGO_DB_PORT}:27017
    volumes:
      - ${MONGO_PATH}:/data/db

  mongo-express:
    image: mongo-express
    restart: ${MONGO_EXPRESS_RESTART}
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_ROOT_PASSWORD}

  vault:
    image: vault
    container_name: vault
    ports:
      - ${VAULT_PORT}:8200
    restart: always
    volumes:
      - ${VAULT_PATH}/volumes/logs:/vault/logs
      - ${VAULT_PATH}/volumes/file:/vault/file
      - ${VAULT_PATH}/volumes/config:/vault/config
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=123123123
    cap_add:
      - IPC_LOCK
#    entrypoint: vault server -config=/vault/config/vault.json

  composer:
    image: composer:1.6
    volumes:
      - ${WEB_ROOT_PATH}:/var/www/html/
    working_dir: ${WEB_WORKING_DIR}
    command: composer update --ignore-platform-reqs
